apiVersion: v1
kind: Service
metadata:
  name: freedom
  labels:
    app: freedom
spec:
  type: LoadBalancer
  selector:
    app: freedom
  ports:  
  - name: http
    port: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: freedom
  labels:
    app: freedom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freedom
  template:
    metadata:
      labels:
        app: freedom
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
