version: '3'
services:
  digitox:
    build: .
    image: jonathanfoster/digitox
    container_name: digitox
    ports:
      - "3128:3128"
      - "8080:8080"
    volumes:
      - digitox:/etc/digitox
volumes:
  digitox:
