version: '3'
services:
  apiserver:
    build: .
    image: jonathanfoster/freedom-apiserver
    container_name: freedom-apiserver
    ports:
      - "8080:8080"
    volumes:
      - squid:/etc/squid
  proxy:
    image: jonathanfoster/squid
    container_name: freedom-proxy
    ports:
      - "3182:3182"
    volumes:
      - squid:/etc/squid
volumes:
  squid:
