version: '3'
services:
  apiserver:
    build: .
    image: digitox/digitox-apiserver
    container_name: digitox-apiserver
    ports:
      - "8080:8080"
    volumes:
      - squid:/etc/squid
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.proxy
    image: digitox/digitox-proxy
    container_name: digitox-proxy
    ports:
      - "3182:3182"
    volumes:
      - squid:/etc/squid
volumes:
  squid:
