apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: freedom
  labels:
    app: freedom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freedom
  template:
    metadata:
      labels:
        app: freedom
    spec:
      containers:
      - name: freedom-apiserver
        image: 672132384976.dkr.ecr.us-east-1.amazonaws.com/freedom/freedom-apiserver:latest
        ports:
        - containerPort: 8080
